spring.application.name=onboarding

server.port=8082

idnow.api.key=abcedefid
idnow.company.id=democompany

idnow.gateway.host_DE=http://localhost:8085
idnow.identification.host_DE=http://localhost:8085

idnow.gateway.host_AE=http://localhost:8085
idnow.identification.host_AE=http://localhost:8085

idnow.gateway.host_CH=http://localhost:8085
idnow.identification.host_CH=http://localhost:8085

auth.uri.path=/api/v1/login